workflows:
  android-workflow:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
    scripts:
      - name: Get dependencies
        script: |
          ./gradlew clean
          ./gradlew build
      - name: Assemble APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
