workflows:
  android-workflow:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Get dependencies
        script: |
          ./gradlew clean
          ./gradlew build
      - name: Assemble APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
