workflows:
  android-debug:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      # Сделать gradlew исполняемым
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      # Получить зависимости и собрать проект
      - name: Get dependencies and build
        script: |
          ./gradlew clean
          ./gradlew assembleDebug

    # Указываем, какие артефакты сохранять
    artifacts:
      - app/build/outputs/**/*.apk
